version: '3.8'

services:
  app:
    build: .
    container_name: go-app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DBNAME=safeDocument
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-db
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
